dst_size = (720, 480)
dst_fps = 15
dst_num_frames = 81
NUM_WORKERS = 1

config = dict(
    dataloaders=dict(
        train=dict(
            dataset=dict(
                type="TensorDataset",
                pth_paths=[
                    "/nvfile-heatstorage/dj/datasets/istock/part_1_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_2_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_3_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_4_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_5_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_6_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_7_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_8_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_9_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_10_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_11_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_12_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_13_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_14_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_15_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_16_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_17_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_18_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_19_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_20_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_21_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_22_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_23_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_24_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_25_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_26_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_27_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_28_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_29_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_30_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_31_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_32_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_33_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_34_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_35_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_36_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_37_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_38_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_39_50000",
                    # "/nvfile-heatstorage/dj/datasets/istock/part_40_50000",
                ],
                metadata_paths=[
                    "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_1_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_2_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_3_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_4_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_5_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_6_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_7_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_8_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_9_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_10_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_11_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_12_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_13_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_14_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_15_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_16_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_17_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_18_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_19_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_20_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_23_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_24_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_25_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_26_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_27_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_28_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_29_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_31_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_32_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_35_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_36_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_37_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_38_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_39_50000.csv",
                    # "/nvfile-heatstorage/dj/datasets/istock/istock_self_forcing/part_40_50000.csv",
                ],
                # only using the above 3 items
                filter_cfg=dict(
                    dst_size=dst_size,
                    dst_num_frames=dst_num_frames,
                    dst_fps=dst_fps,
                    multiple=16,
                    min_area=dst_size[0] * dst_size[1],
                    optical_flow_th=4,
                    aesthetic_th=4.5,
                    bucket_size_th=4,
                    motion_th=0,
                    clearity_th=0.9,
                    laplacian_th=200,
                    training_suitability_th=5.0,
                    area_th=1280 * 720,
                ),

                transforms=[
                    dict(
                        type="SampleImages",
                        num_frames=dst_num_frames,
                    ),
                    dict(
                        type="PromptGenerator",
                        clean_prompt=True,
                        default_prompt_prob=0.1,
                    ),
                    dict(
                        type="PackInputs",
                        image_keys=[
                            "images",
                        ],
                        #dst_size=dst_size,
                    ),
                    dict(
                        type="GenerateRefImagesWithMask",
                        mask_cfg={
                            "t2v": 0.0,
                            "i2v": 0.4,
                            "clear": 0.0,
                            "continuation": 0.2,
                            "random": 0.0,
                            "transition": 0.4
                        },
                        min_clear_ratio=0.0,
                        max_clear_ratio=1.0,
                    ),
                ],
            ),
            batch_size_per_gpu=1,
            num_workers=NUM_WORKERS,
            sampler=dict(
                type="DefaultSampler",
            ),
            collator=dict(
                is_equal=True,
            ),
        ),
    ),
)
