import os
import math

dst_size = (832, 480)
dst_fps = 16
dst_num_frames = 81

config = dict(
    dataset=dict(
        type="ClipDataset",
        serialize_data=False,
        data_path_list=[
            "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_0.json",
            "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_1.json",
            "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_2.json",
            "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_3.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_4.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_5.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_6.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_7.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_8.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_9.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_10.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_11.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_12.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_13.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_14.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_15.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_16.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_17.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_18.json",
            # "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_19.json",             
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_0.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_1.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_2.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_3.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_4.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_5.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_6.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_7.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/xhzx/xhzx_8.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/zwzx/zwzx_0.json',
            # '/nvfile-heatstorage/cjf/share/data/0617/zwzx/zwzx_1.json',
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_0.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_1.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_2.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_3.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_4.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_5.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_6.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_7.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_8.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_9.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_10.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_11.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_12.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_13.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_14.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_15.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_16.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_17.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_18.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_19.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_20.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_21.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_22.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_23.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_24.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_25.json",
            # "/nvfile-heatstorage/cjf/share/data/0625/istock3_clips/istock3_clips_26.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_0.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_1.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_2.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_3.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_4.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_5.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_6.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_7.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_8.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_9.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_10.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_11.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_12.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_13.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_14.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_15.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_16.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_17.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_18.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_19.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_20.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_21.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_22.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_23.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_24.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_25.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_26.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_27.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_28.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_29.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_30.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_31.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_32.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_33.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_34.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_35.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_36.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_37.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_38.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_39.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_40.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_41.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_42.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_43.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_44.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_45.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_46.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_47.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_48.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_49.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_50.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_51.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_52.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_53.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_54.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_55.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_56.json",
            # "/nvfile-heatstorage/cjf/share/data/0630/istock4/istock4_57.json",
        ],
        filter_cfg=dict(
            dst_size=dst_size,
            dst_num_frames = dst_num_frames,
            dst_fps = dst_fps,
            multiple=16,
            min_area=dst_size[0] * dst_size[1] * (2 if dst_size[1] == 480 else 1),
            optical_flow_th=1.5,
            aesthetic_th=5,
            bucket_size_th=4,
            motion_th=0,
            clearity_th=0.9,
            laplacian_th=30,
            training_suitability_th=5.0,
            area_th=dst_size[0] * dst_size[1] * (2 if dst_size[1] == 480 else 1),
        ),
        transforms=[
            dict(
                type="SampleImages",
                num_frames=dst_num_frames,
            ),
            dict(
                type="PromptGenerator",
                clean_prompt=True,
                default_prompt_prob=0.1,
            ),
            dict(
                type="GenerateRawFirstRefImage",
            ),
            dict(
                type="PackInputs",
                deterministic=True,
                image_keys=[
                    "images",
                ],
                embedding_keys=[
                    "raw_first_image", 
                ],  
            ),
        ],
    ),
    eval=dict(
        data_path_list=[
            "/nvfile-heatstorage/cjf/share/export_to_clipdataset/istock/istock_0.json",
        ],
    ),
)
