hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

trainer:
  type: diffusion

data:
  type: diffusion

actor_rollout_ref:
  model:
    vae_model_path: data/flux
    data_json_path: data/rl_embeddings/videos2caption.json
  cfg: 0.0
  h: 720
  w: 720
  num_frames: 1
  sampling_steps: 16
  eta: 0.3
  lr_warmup_steps: 0
  use_hpsv2: True
  shift: 3
  timestep_fraction: 0.6
  init_same_noise: True
  clip_range: 1e-4
  adv_clip_max: 5.0