hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - dancegrpo_trainer
  - _self_

actor_rollout_ref:
  pixel_weight:
    enable: true
    model_path: ./dinov2-large
    pca_method: weighted
    sigma: 1.0
